# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2e998895e142a22161b7461681245dfc9473de90b54b2ec3ba0d27800e87b6b32f40fcce429eccb46e8ee2b99418794f8fa21aae5e4c3f798f3646b55029abb

test:
  secret_key_base: c234bc6e140c9df53733c8c7f2bc601737b43801ad39ad382056968e132be257a7ac1f4d58fa42e7aa94acf46c51b8ddefad2de0e00e5a7b8cea96b806832d0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
